### ISSUE TITLE
Implement as part of core Stream api?

### ISSUE THREAD

**Issue by brianegan** [dart-lang/stream_transform#40]
Heya @natebosch!

Just checked up on the progress on this package, very cool :) I also re-read the package vision doc from a while back, and it got me thinking: Is there any way we could move these from a third-party package into the core Stream Api?

I started working on RxDart with Frank b/c I felt the core Stream API was simply missing a lot of features I needed (concatenating, zipping, flatMapping / Latest, really core features IMO to developing UIs with Streams and probably other things). It seems I'm not the only one, as in addition to this package, there are several implementations of these same StreamTransformers in various packages:

  - RxDart
  - Frappe
  - stream_ext
  - The `async` package even has things like `StreamZip`

Given that the community keeps reinventing the wheel here, demonstrating a clear need for these transformers, and since this package resides under the dart-lang org, I was wondering if it was possible to simply move many of these into the core Stream API, or if we could advocate together for such a change to the core API? 

I think this would reduce the duplicated effort across so many packages and give Dart a better core async lib. Any thoughts?

**Comment by natebosch** [comment]
What would be really cool is if Dart had extension methods so we could publish these outside the SDK but still use them on streams without the `.transform` calls :smile: 

There are definitely some things that might be nice in the core SDK. One of the things that packages like this help us to do is to evaluate the utility and usability of some of these things before committing to them as deeply as the SDK. If there are any pieces which stand out as particularly useful we could take a look at moving them to the Stream api.

We do have to be careful about what we put in the SDK - there is a pretty high cost to expanding those libraries in terms of cognitive load, inability to make breaking changes, and adding to the noise newcomers need to dig through to find out the really useful ways to use streams.
It's also tough because some code, wisely or unwisely, `implements Stream` which means that adding new methods ends up being a breaking change. We hit this a while back trying to add `groupBy` to Stream.

The core library team is definitely aware of the spread of these types of packages and I'm sure that anything that bubbles up as the most useful will get evaluated for inclusion in the SDK. It's possible we might see the Stream API grow with Dart 2.0
